### ISSUE TITLE
Get ps1 and example working for windows

### ISSUE THREAD

**Issue by winwisely99** [winwisely99/bootstrap#2]
1. Edit the ps1 so that EVERYTHING at OS dependency level gets installed

The idea if that the Project Makefiles then dont need to do any OS installs.

If you EVER find you need a native OS thing ( like protoc ) then add it to the ps1, but ONLY if there is the equivalent for MAC and Linux.

Make sure the other MAC and LINUX stuff habe the same things, and add a TODO comment if not.

2. Test the flutter and go examples work for you.

3. Prove it works. Add the Log output into the Issue

**Comment by thevzurd** [comment]
I am skipping PS1 as I have already ran it once yesterday.

Go Examples - >
![image](https://user-images.githubusercontent.com/31169070/68480592-307edf80-0203-11ea-8187-053035e2da19.png)

![image](https://user-images.githubusercontent.com/31169070/68480613-3c6aa180-0203-11ea-8db5-e0da14b97312.png)

![image](https://user-images.githubusercontent.com/31169070/68480651-5310f880-0203-11ea-9e59-d1cce1241d0f.png)

![image](https://user-images.githubusercontent.com/31169070/68480670-5ad09d00-0203-11ea-8e14-93100e74fb97.png)

**Comment by thevzurd** [comment]
go example

![image](https://user-images.githubusercontent.com/31169070/68481351-f7476f00-0204-11ea-9fe7-fa004938bc69.png)

![image](https://user-images.githubusercontent.com/31169070/68481371-03cbc780-0205-11ea-8bce-752427ad2e9a.png)

![image](https://user-images.githubusercontent.com/31169070/68481390-11814d00-0205-11ea-8af6-f1f02f2e580f.png)

**Comment by winwisely99** [comment]
@thevzurd 

Not for collab. Use the output not screenshots.
I cant even see all screens because they are too big.


```
log

```

**Comment by winwisely99** [comment]
Can you run the PS1 and put the output here ?

Its idempotent.. so running it again  DOES nothing.

Also how did you install glfw ?

**Comment by winwisely99** [comment]
The reason i ask about glfw is because it fails on windows here:

SO i need to know how you installed it

https://github.com/winwisely99/bootstrap/runs/294580648

**Comment by thevzurd** [comment]
`PS C:\WINDOWS\system32> C:\Programs\Flutter\flutter_windows_v0.8.2-beta\Projects\winwisely99\bootstrap-master\win\bootstrap.ps1
Updating Scoop...
Updating 'extras' bucket...
Updating 'main' bucket...
Scoop was updated successfully!
WARN  'aria2' (1.35.0-1) is already installed.
Use 'scoop update aria2' to install a new version.
WARN  The 'extras' bucket already exists. Use 'scoop bucket rm extras' to remove it.
WARN  'git' (2.24.0.windows.2) is already installed.
Use 'scoop update git' to install a new version.
WARN  'which' (2.20) is already installed.
Use 'scoop update which' to install a new version.
WARN  'make' (4.2.1) is already installed.
Use 'scoop update make' to install a new version.
WARN  'go' (1.13.4) is already installed.
Use 'scoop update go' to install a new version.
WARN  'protobuf' (3.10.1) is already installed.
Use 'scoop update protobuf' to install a new version.
WARN  'gcc' (8.1.0) is already installed.
Use 'scoop update gcc' to install a new version.
Checking repo... ok
The java bucket was added successfully.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'adb' (29.0.5) [64bit]
Starting download with aria2 ...
Download: [#83d8f2 5.9MiB/6.8MiB(87%) CN:1 DL:7.3MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 83d8f2|OK  |   7.2MiB/s|C:/Users/thevz/scoop/cache/adb#29.0.5#https_dl.google.com_android_repository_platform-tools_r29.0.5-
windows.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of platform-tools_r29.0.5-windows.zip ... ok.
Extracting platform-tools_r29.0.5-windows.zip ... done.
Linking ~\scoop\apps\adb\current => ~\scoop\apps\adb\29.0.5
Creating shim for 'adb'.
Creating shim for 'dmtracedump'.
Creating shim for 'etc1tool'.
Creating shim for 'fastboot'.
Creating shim for 'hprof-conv'.
'adb' (29.0.5) was installed successfully!
Installing 'android-sdk' (4333796) [64bit]
Starting download with aria2 ...
Download: [#658f50 6.4MiB/148MiB(4%) CN:5 DL:10MiB ETA:13s]
Download: [#658f50 15MiB/148MiB(10%) CN:5 DL:9.8MiB ETA:13s]
Download: [#658f50 26MiB/148MiB(17%) CN:5 DL:10MiB ETA:12s]
Download: [#658f50 35MiB/148MiB(23%) CN:5 DL:9.8MiB ETA:11s]
Download: [#658f50 45MiB/148MiB(30%) CN:5 DL:9.8MiB ETA:10s]
Download: [#658f50 55MiB/148MiB(37%) CN:5 DL:9.9MiB ETA:9s]
Download: [#658f50 64MiB/148MiB(43%) CN:5 DL:9.7MiB ETA:8s]
Download: [#658f50 72MiB/148MiB(48%) CN:5 DL:9.4MiB ETA:8s]
Download: [#658f50 85MiB/148MiB(57%) CN:5 DL:9.8MiB ETA:6s]
Download: [#658f50 94MiB/148MiB(63%) CN:5 DL:9.8MiB ETA:5s]
Download: [#658f50 102MiB/148MiB(68%) CN:5 DL:9.6MiB ETA:4s]
Download: [#658f50 110MiB/148MiB(74%) CN:5 DL:9.0MiB ETA:4s]
Download: [#658f50 121MiB/148MiB(81%) CN:5 DL:8.8MiB ETA:3s]
Download: [#658f50 131MiB/148MiB(88%) CN:5 DL:8.4MiB ETA:2s]
Download: [#658f50 142MiB/148MiB(95%) CN:2 DL:8.6MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 658f50|OK  |   9.0MiB/s|C:/Users/thevz/scoop/cache/android-sdk#4333796#https_dl.google.com_android_repository_sdk-tools-wind
ows-4333796.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of sdk-tools-windows-4333796.zip ... ok.
Extracting sdk-tools-windows-4333796.zip ... done.
Linking ~\scoop\apps\android-sdk\current => ~\scoop\apps\android-sdk\4333796
Creating shim for 'proguard'.
Creating shim for 'proguardgui'.
Creating shim for 'retrace'.
Creating shim for 'emulator'.
Creating shim for 'emulator-check'.
Creating shim for 'mksdcard'.
Creating shim for 'monitor'.
Persisting .knownPackages
Persisting build-tools
Persisting emulator
Persisting extras
Persisting licenses
Persisting patcher
Persisting platforms
Persisting sources
Running post-install script...
'android-sdk' (4333796) was installed successfully!
Installing 'adopt8-hotspot' (8u232-b09) [64bit]
Starting download with aria2 ...
Download: [#d29538 512KiB/99MiB(0%) CN:5 DL:1.8MiB ETA:53s]
Download: [#d29538 3.3MiB/99MiB(3%) CN:5 DL:2.6MiB ETA:36s]
Download: [#d29538 9.2MiB/99MiB(9%) CN:5 DL:4.0MiB ETA:22s]
Download: [#d29538 15MiB/99MiB(15%) CN:5 DL:4.7MiB ETA:17s]
Download: [#d29538 21MiB/99MiB(21%) CN:5 DL:5.0MiB ETA:15s]
Download: [#d29538 26MiB/99MiB(26%) CN:5 DL:5.0MiB ETA:14s]
Download: [#d29538 33MiB/99MiB(33%) CN:5 DL:5.3MiB ETA:12s]
Download: [#d29538 39MiB/99MiB(40%) CN:5 DL:5.4MiB ETA:10s]
Download: [#d29538 45MiB/99MiB(46%) CN:5 DL:5.5MiB ETA:9s]
Download: [#d29538 51MiB/99MiB(51%) CN:5 DL:5.5MiB ETA:8s]
Download: [#d29538 57MiB/99MiB(57%) CN:5 DL:5.9MiB ETA:7s]
Download: [#d29538 61MiB/99MiB(61%) CN:5 DL:5.8MiB ETA:6s]
Download: [#d29538 64MiB/99MiB(64%) CN:5 DL:5.4MiB ETA:6s]
Download: [#d29538 68MiB/99MiB(68%) CN:5 DL:5.2MiB ETA:5s]
Download: [#d29538 72MiB/99MiB(72%) CN:5 DL:5.0MiB ETA:5s]
Download: [#d29538 75MiB/99MiB(76%) CN:5 DL:4.7MiB ETA:4s]
Download: [#d29538 78MiB/99MiB(78%) CN:5 DL:4.3MiB ETA:4s]
Download: [#d29538 83MiB/99MiB(83%) CN:5 DL:4.1MiB ETA:4s]
Download: [#d29538 86MiB/99MiB(87%) CN:4 DL:3.8MiB ETA:3s]
Download: [#d29538 89MiB/99MiB(90%) CN:3 DL:3.5MiB ETA:2s]
Download: [#d29538 92MiB/99MiB(92%) CN:2 DL:3.3MiB ETA:2s]
Download: [#d29538 94MiB/99MiB(95%) CN:2 DL:3.2MiB ETA:1s]
Download: [#d29538 97MiB/99MiB(97%) CN:1 DL:3.1MiB]
Download: [#d29538 99MiB/99MiB(99%) CN:1 DL:2.9MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: d29538|OK  |   4.2MiB/s|C:/Users/thevz/scoop/cache/adopt8-hotspot#8u232-b09#https_github.com_AdoptOpenJDK_openjdk8-binaries_
releases_download_jdk8u232-b09_OpenJDK8U-jdk_x64_windows_hotspot_8u232b09.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of OpenJDK8U-jdk_x64_windows_hotspot_8u232b09.zip ... ok.
Extracting OpenJDK8U-jdk_x64_windows_hotspot_8u232b09.zip ... done.
Linking ~\scoop\apps\adopt8-hotspot\current => ~\scoop\apps\adopt8-hotspot\8u232-b09
'adopt8-hotspot' (8u232-b09) was installed successfully!
Installing 'flutter' (1.5.4-hotfix.2) [64bit]
Starting download with aria2 ...
Download: [#937da9 0B/470MiB(0%) CN:1 DL:0B] [FileAlloc:#937da9 192MiB/470MiB(40%)]
Download: [#937da9 3.0MiB/470MiB(0%) CN:5 DL:6.4MiB ETA:1m12s]
Download: [#937da9 14MiB/470MiB(3%) CN:5 DL:10MiB ETA:45s]
Download: [#937da9 26MiB/470MiB(5%) CN:5 DL:10MiB ETA:41s]
Download: [#937da9 37MiB/470MiB(8%) CN:5 DL:10MiB ETA:39s]
Download: [#937da9 48MiB/470MiB(10%) CN:5 DL:10MiB ETA:39s]
Download: [#937da9 56MiB/470MiB(11%) CN:5 DL:10MiB ETA:40s]
Download: [#937da9 64MiB/470MiB(13%) CN:5 DL:9.9MiB ETA:40s]
Download: [#937da9 72MiB/470MiB(15%) CN:5 DL:9.7MiB ETA:40s]
Download: [#937da9 77MiB/470MiB(16%) CN:5 DL:9.1MiB ETA:43s]
Download: [#937da9 83MiB/470MiB(17%) CN:5 DL:8.7MiB ETA:44s]
Download: [#937da9 98MiB/470MiB(20%) CN:5 DL:9.2MiB ETA:40s]
Download: [#937da9 107MiB/470MiB(22%) CN:5 DL:9.1MiB ETA:39s]
Download: [#937da9 116MiB/470MiB(24%) CN:5 DL:8.7MiB ETA:40s]
Download: [#937da9 122MiB/470MiB(26%) CN:5 DL:8.1MiB ETA:42s]
Download: [#937da9 133MiB/470MiB(28%) CN:5 DL:8.0MiB ETA:41s]
Download: [#937da9 146MiB/470MiB(31%) CN:5 DL:8.5MiB ETA:37s]
Download: [#937da9 154MiB/470MiB(32%) CN:5 DL:8.4MiB ETA:37s]
Download: [#937da9 164MiB/470MiB(34%) CN:5 DL:8.9MiB ETA:34s]
Download: [#937da9 174MiB/470MiB(37%) CN:5 DL:8.8MiB ETA:33s]
Download: [#937da9 187MiB/470MiB(39%) CN:5 DL:8.8MiB ETA:32s]
Download: [#937da9 199MiB/470MiB(42%) CN:5 DL:8.8MiB ETA:30s]
Download: [#937da9 207MiB/470MiB(44%) CN:4 DL:8.8MiB ETA:29s]
Download: [#937da9 217MiB/470MiB(46%) CN:5 DL:8.7MiB ETA:29s]
Download: [#937da9 230MiB/470MiB(49%) CN:5 DL:8.7MiB ETA:27s]
Download: [#937da9 239MiB/470MiB(50%) CN:5 DL:8.8MiB ETA:26s]
Download: [#937da9 250MiB/470MiB(53%) CN:5 DL:8.9MiB ETA:24s]
Download: [#937da9 258MiB/470MiB(54%) CN:5 DL:8.6MiB ETA:24s]
Download: [#937da9 270MiB/470MiB(57%) CN:5 DL:8.7MiB ETA:22s]
Download: [#937da9 282MiB/470MiB(60%) CN:5 DL:9.0MiB ETA:20s]
Download: [#937da9 296MiB/470MiB(63%) CN:5 DL:9.4MiB ETA:18s]
Download: [#937da9 309MiB/470MiB(65%) CN:5 DL:9.9MiB ETA:16s]
Download: [#937da9 316MiB/470MiB(67%) CN:5 DL:9.3MiB ETA:16s]
Download: [#937da9 323MiB/470MiB(68%) CN:5 DL:9.1MiB ETA:16s]
Download: [#937da9 330MiB/470MiB(70%) CN:5 DL:8.5MiB ETA:16s]
Download: [#937da9 337MiB/470MiB(71%) CN:5 DL:8.6MiB ETA:15s]
Download: [#937da9 344MiB/470MiB(73%) CN:5 DL:8.4MiB ETA:15s]
Download: [#937da9 349MiB/470MiB(74%) CN:5 DL:8.0MiB ETA:14s]
Download: [#937da9 354MiB/470MiB(75%) CN:5 DL:7.3MiB ETA:15s]
Download: [#937da9 362MiB/470MiB(77%) CN:4 DL:6.9MiB ETA:15s]
Download: [#937da9 369MiB/470MiB(78%) CN:5 DL:6.3MiB ETA:15s]
Download: [#937da9 379MiB/470MiB(80%) CN:5 DL:6.7MiB ETA:13s]
Download: [#937da9 387MiB/470MiB(82%) CN:5 DL:6.4MiB ETA:12s]
Download: [#937da9 394MiB/470MiB(83%) CN:5 DL:6.5MiB ETA:11s]
Download: [#937da9 399MiB/470MiB(85%) CN:5 DL:6.3MiB ETA:11s]
Download: [#937da9 409MiB/470MiB(86%) CN:5 DL:7.1MiB ETA:8s]
Download: [#937da9 416MiB/470MiB(88%) CN:5 DL:7.1MiB ETA:7s]
Download: [#937da9 423MiB/470MiB(89%) CN:5 DL:7.2MiB ETA:6s]
Download: [#937da9 427MiB/470MiB(90%) CN:5 DL:6.8MiB ETA:6s]
Download: [#937da9 438MiB/470MiB(93%) CN:5 DL:7.4MiB ETA:4s]
Download: [#937da9 444MiB/470MiB(94%) CN:4 DL:7.1MiB ETA:3s]
Download: [#937da9 450MiB/470MiB(95%) CN:4 DL:6.9MiB ETA:2s]
Download: [#937da9 454MiB/470MiB(96%) CN:3 DL:6.5MiB ETA:2s]
Download: [#937da9 459MiB/470MiB(97%) CN:3 DL:6.5MiB ETA:1s]
Download: [#937da9 462MiB/470MiB(98%) CN:3 DL:5.8MiB ETA:1s]
Download:  *** Download Progress Summary as of Fri Nov 08 15:21:22 2019 *** 
Download: ===============================================================================
Download: [#937da9 464MiB/470MiB(98%) CN:2 DL:5.3MiB ETA:1s]
Download: FILE: C:/Users/thevz/scoop/cache/flutter#1.5.4-hotfix.2#https_storage.googleapis.com_flutter_infra_releases_stable_windows_f
lutter_windows_v1.5.4-hotfix.2-stable.zip
Download: -------------------------------------------------------------------------------
Download: [#937da9 464MiB/470MiB(98%) CN:2 DL:5.3MiB ETA:1s]
Download: [#937da9 467MiB/470MiB(99%) CN:2 DL:4.8MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: fc9203|OK  |   312KiB/s|C:/Users/thevz/scoop/cache/flutter#1.5.4-hotfix.2#https_raw.githubusercontent.com_lukesampson_scoop-
extras_master_scripts_flutter-dev-setup.ps1
Download: 937da9|OK  |   7.7MiB/s|C:/Users/thevz/scoop/cache/flutter#1.5.4-hotfix.2#https_storage.googleapis.com_flutter_infra_release
s_stable_windows_flutter_windows_v1.5.4-hotfix.2-stable.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of flutter_windows_v1.5.4-hotfix.2-stable.zip ... ok.
Checking hash of flutter-dev-setup.ps1 ... ok.
Extracting flutter_windows_v1.5.4-hotfix.2-stable.zip ... done.
Linking ~\scoop\apps\flutter\current => ~\scoop\apps\flutter\1.5.4-hotfix.2
Creating shim for 'flutter'.
Creating shim for 'flutter-dev-setup'.
Running post-install script...
WARNING: Ping to 13.107.4.52 failed with status: TimedOut
flutter-dev-setup.ps1 could not connect to the internet. Please connect to the internet and try again, or install flutter requirements
 manually.
Some licenses need to be accepted before developing. We recommend you do so by running flutter doctor --android-licenses .
  â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•—
  â•‘ A new version of Flutter is available!                                     â•‘
  â•‘                                                                            â•‘
  â•‘ To update to the latest version, run "flutter upgrade".                    â•‘
  â•šâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

Doctor summary (to see all details, run flutter doctor -v):
[âˆš] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.805], locale en-CA)
[!] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    X No valid Android SDK platforms found in C:\Users\thevz\scoop\apps\android-sdk\current\platforms. Directory was empty.
[âˆš] Android Studio (version 3.5)
[âˆš] VS Code, 64-bit edition (version 1.39.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
'flutter' (1.5.4-hotfix.2) was installed successfully!
Notes
-----
Flutter has been successfully installed and put in your PATH.
If using Visual Studio Code, don't forget to install the Flutter Extension!
Then connect an Android Phone and start coding :-)
'flutter' suggests installing 'vscode' or 'vscode-portable'.`

**Comment by thevzurd** [comment]
Scoop was already installed in my system. so I had to comment the scoop install as it was not executing further after the install scoop step.
